/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.satokano.proxyclass;

import org.junit.Test;

import com.github.satokano.proxyclass.fw.AppRunner;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        AppRunner classUnderTest = new AppRunner();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
